name: Pylint

on:
  pull_request:
    paths:
      - 'package/**.py'
      - 'requirements.txt'
      - 'pyproject.toml'
      - '.github/workflows/pylint.yml'
  push:
    branches: [ "master", "main" ]
    paths:
      - 'package/**.py'
      - 'requirements.txt'
      - 'pyproject.toml'
      - '.github/workflows/pylint.yml'

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      timeout-minutes: 10
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade build typing_extensions setuptools matplotlib pylint -r requirements.txt
    - name: Analysing the code with pylint
      timeout-minutes: 10
      run: |
        pylint \
          --output-format=colorized \
          --max-line-length=127 \
          $(git ls-files 'package/**/*.py')
